### PR TITLE
fix: remove thread local based wiring

### LINKED ISSUE #1812: Failed to wire ComponentClient
I got this error today (once locally, once in prod).

It fails to inject a `ComponentClient` into a `UserEventsListener`, but `UserEventsListener` is an Action so it should just work. There is probably a race condition causing this.

```
2023-10-18 23:33:53.812 app[service-6fdcf8db9d-6h7rw] ERROR k.java.impl.action.ActionsImpl Failure during handling of command user.registry.components.actions.UserEventsListener.KalixSyntheticMethodOnESUser
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'user.registry.components.actions.UserEventsListener' defined in URL [jar:file:/maven/user-registry-1.0-SNAPSHOT.jar!/BOOT-INF/classes!/user/registry/components/actions/UserEventsListener.class]: Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'componentClient': FactoryBean threw exception on object creation
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:245)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1352)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1189)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:560)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:344)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:225)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveNamedBean(DefaultListableBeanFactory.java:1310)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveNamedBean(DefaultListableBeanFactory.java:1271)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveBean(DefaultListableBeanFactory.java:484)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:339)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:332)
	at kalix.spring.impl.KalixSpringApplication.$anonfun$actionProvider$1(KalixSpringApplication.scala:403)
	at kalix.javasdk.action.ReflectiveActionProvider.newRouter(ReflectiveActionProvider.java:76)
	at kalix.javasdk.impl.action.ActionsImpl.handleUnary(ActionsImpl.scala:199)
	at kalix.protocol.action.ActionsHandler$.$anonfun$partial$2(ActionsHandler.scala:118)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:470)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'componentClient': FactoryBean threw exception on object creation
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:154)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:90)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1823)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getObjectForBeanInstance(AbstractAutowireCapableBeanFactory.java:1273)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:259)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.addCandidateEntry(DefaultListableBeanFactory.java:1640)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1597)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1380)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1337)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:888)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
	... 29 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: ComponentClient can only be injected in Kalix Actions and Workflows.
	at kalix.spring.impl.KalixSpringApplication$ComponentClientFactoryBean$.getObject(KalixSpringApplication.scala:246)
	at kalix.spring.impl.KalixSpringApplication$ComponentClientFactoryBean$.getObject(KalixSpringApplication.scala:240)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:148)
	... 41 common frames omitted
```

### PR DESCRIPTION
**Pull request by octonato**
Fix #1812

### CODE REVIEW

File: sdk/java-sdk-spring/src/test/java/kalix/spring/badwiring/workflow/IllDefinedWorkflow.java [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+ * limitations under the License.
+ */
+
+package kalix.spring.badwiring.workflow;
+
+import kalix.javasdk.workflow.Workflow;
+import org.springframework.stereotype.Component;
+
+@Component
+public class IllDefinedWorkflow extends Workflow<String> {
```
Comment (octonato) [inline sdk/java-sdk-spring/src/test/java/kalix/spring/badwiring/workflow/IllDefinedWorkflow.java:23]: This class and the one below are not related to the fix, but we were missing this test for Worklows

File: sdk/java-sdk-spring/src/main/scala/kalix/spring/impl/KalixSpringApplication.scala [hunk 2]
```diff
@@ -368,88 +299,106 @@ case class KalixSpringApplication(applicationContext: ApplicationContext, config
...
+
+    // Note that this function is total because it will always return a value (even if null)
+    // last case is a catch all that lookups in the applicationContext
+    val totalWireFunction: PartialFunction[Class[_], Any] =
+      partial.orElse {
+        // block wiring of clients into anything that is not an Action or Workflow
+        // NOTE: if they are allowed, 'partial' should already have a matching case for them
+        case p if p == classOf[KalixClient] =>
+          new BeanCreationException(
+            s"KalixClient cannot be inject into a [${constructor.getDeclaringClass.getSimpleName}]")
```
Comment (johanandren) [inline sdk/java-sdk-spring/src/main/scala/kalix/spring/impl/KalixSpringApplication.scala:323]: It should just create and return the exception, not throw it?

Comment (octonato) [reply sdk/java-sdk-spring/src/main/scala/kalix/spring/impl/KalixSpringApplication.scala:323]: Oh god! I don't know how to code anymore.

File: sdk/java-sdk-spring/src/main/scala/kalix/spring/impl/KalixSpringApplication.scala [hunk 3]
```diff
@@ -368,88 +299,101 @@ case class KalixSpringApplication(applicationContext: ApplicationContext, config
...
+  private def wiredInstance[T](constructor: Constructor[T])(partial: PartialFunction[Class[_], Any]): T = {
+
+    // Note that this function is total because it will always return a value (even if null)
+    // last case is a catch all that lookups in the applicationContext
+    val totalWireFunction: PartialFunction[Class[_], Any] =
+      partial.orElse {
+        // block wiring of clients into anything that is not an Action or Workflow
+        // NOTE: if they are allowed, 'partial' should already have a matching case for them
+        case p if p == classOf[KalixClient] =>
+          throw new BeanCreationException(
```
Comment (octonato) [inline sdk/java-sdk-spring/src/main/scala/kalix/spring/impl/KalixSpringApplication.scala:335]: Look @johanandren, now throwing for real.

File: sdk/java-sdk-spring/src/main/scala/kalix/spring/impl/KalixSpringApplication.scala [hunk 4]
```diff
@@ -368,88 +299,101 @@ case class KalixSpringApplication(applicationContext: ApplicationContext, config
...
+            s"[${constructor.getDeclaringClass.getSimpleName}] are not allowed to have a dependency on KalixClient")
```
Comment (octonato) [inline sdk/java-sdk-spring/src/main/scala/kalix/spring/impl/KalixSpringApplication.scala:336]: I re-phrased the text here because I was using the article 'a' in previous commit. It would be wrong for EventSourcedEntity.

File: sdk/java-sdk-spring/src/main/scala/kalix/spring/impl/KalixSpringApplication.scala [hunk 5]
```diff
@@ -368,88 +299,101 @@ case class KalixSpringApplication(applicationContext: ApplicationContext, config
...
+        case p if p == classOf[WebClientProvider] =>
+          throw new BeanCreationException(
+            s"[${constructor.getDeclaringClass.getSimpleName}] are not allowed to have a dependency on WebClientProvider")
+
+        // if partial func doesn't match, try to lookup in the applicationContext
+        case anyOther =>
+          val bean = applicationContext.getBean(anyOther)
+          if (bean == null)
+            throw new BeanCreationException(
+              s"Cannot wire [${anyOther.getSimpleName}]. Bean not found in the Application Context");
```
Comment (octonato) [inline sdk/java-sdk-spring/src/main/scala/kalix/spring/impl/KalixSpringApplication.scala:351]: I also remove the check on wiring wrong context.

This more generic check will cover all wrong contexts, but also cases in which the user didn't properly define their own bean.

Comment (octonato) [reply sdk/java-sdk-spring/src/main/scala/kalix/spring/impl/KalixSpringApplication.scala:351]: We can go one extra mile and provide specific error messages when a user tries to inject a ActionContext into an EventSourcedEntity, for example. 

But maybe that's something we should do using our Validation frameworky.

**Review by johanandren — APPROVED** [review]
