### PR TITLE
fix: fail to publish docs on release

### LINKED ISSUE #1250: Documentation deploy is broken
When releasing 1.0.11 (refs https://github.com/lightbend/kalix-jvm-sdk/issues/1249) the publish-docs broke with:
```shell
error: missing required argument: upstream
make: *** [Makefile:115: deploy] Error 1
```

I would guess this might be related with some changes we did for fitting in Spring docs but couldn't spot any obvious problem right away.

See pipeline [here](https://app.circleci.com/pipelines/github/lightbend/kalix-jvm-sdk/4803/workflows/0ca35637-ebe9-48b7-8f57-4271dba651a8/jobs/81414).

### PR DESCRIPTION
**Pull request by efgpinto**
Fix #1250

Follow-up of https://github.com/lightbend/kalix-jvm-sdk/pull/1199

### CODE REVIEW

File: docs/Makefile [hunk 1]
```diff
@@ -112,5 +112,6 @@ validate-links:
 		-t ${antora_docker_image}:${antora_docker_image_tag} \
 		-c "cd /antora/${base_path} && find src -name '*.adoc' -print0 | xargs -0 -n1 asciidoc-link-check --progress --config config/validate-links.json"
 
+# TODO: we will need to include publication for spring module once we want it out
 deploy: clean managed
-	bin/deploy.sh --module ${module} --upstream ${upstream} --branch ${branch} ${sources}
+	bin/deploy.sh --module java --upstream ${upstream} --branch ${branch} ${sources}
```
Comment (efgpinto) [inline docs/Makefile:117]: Declaration of `$module` was removed in https://github.com/lightbend/kalix-jvm-sdk/pull/1199

We'll need to publish once for each module once we add spring officially or do a larger refactor of the deploy script.

File: docs/bin/deploy.sh [hunk 2]
```diff
@@ -15,7 +15,7 @@
 # deploy author
 
 readonly deploy_name="Kalix Bot"
-readonly deploy_email="bot@kalix.io"
+readonly deploy_email="kalix.github@lightbend.com"
```
Comment (efgpinto) [inline docs/bin/deploy.sh:18]: That email did not exist, updating to the one associated with the Kalix Bot.

**Review by octonato — APPROVED** [review]
LGTM
